name: statistics-resampling-online
channels:
  - conda-forge
dependencies:
  - nbgitpuller
  # GNU Octave for JupyterLab
  - octave
  - octave_kernel
  # For compiling packages
  - compilers
  - make
  # Spreadsheet editor for JupyterLab
  - jupyterlab-spreadsheet-editor
  # R (including package manager)
  - r-base
