name: Binder-jammy
on: 
  push:
    branches:
      - jammy

jobs:
  Create-MyBinderOrg-Cache:
    runs-on: ubuntu-latest
    steps:
    - name: cache binder build on mybinder.org
      uses: acpennlab/repo2docker-action@jammy
      with:
        NO_PUSH: true
        MYBINDERORG_TAG: ${{ github.event.ref }} # This builds the container on mybinder.org with the branch that was pushed on.
        FORCE_REPO2DOCKER_VERSION: jupyter-repo2docker==2023.6.0
        REPO2DOCKER_EXTRA_ARGS: --Repo2Docker.base_image=docker.io/library/buildpack-deps:jammy
